### ISSUE TITLE
Server disconnect issue

### ISSUE THREAD

**Issue by TheButterbrotMan** [chimericdream/minekea-fabric#47] opened 2022-06-16 15:07 UTC
When i add this mod to my modpack and load a world on a server, i cant connect to it. I am getting this error
![unknown](https://user-images.githubusercontent.com/64548098/174101282-dbc769a0-be5d-445d-98b6-da66e8e0542b.png)
:

**Comment by TheButterbrotMan** [comment] 2022-06-16 15:47
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheButterbrotMan** [comment] 2022-06-16 15:48
Its version 1.18.2, on fabric, with modversion 2.8.2.

**Comment by TheButterbrotMan** [comment] 2022-06-16 15:50
Some players was also able to produce this bug with the current 2.0.9 version of my modpack. But i was unable to reproduce it.

**Comment by chimericdream** [comment] 2022-06-17 03:08
Actually, I may have just figured out the issue. It may be caused by the sheer volume of recipes in the pack. I tried searching for the error message, and I found this issue in the Forge repository. I realize that this is a Fabric mod and modpack, but I can't help wondering if Fabric has the same limitation.

https://github.com/MinecraftForge/MinecraftForge/issues/6703

As a matter of fact, it looks like this might be a bug in Minecraft itself:

https://bugs.mojang.com/browse/MC-185901

**Comment by TheButterbrotMan** [comment] 2022-06-17 09:49
Try with 2.0.10, and update minekea to latest update there. This should make it reproduce able.

**Comment by chimericdream** [comment] 2022-06-17 20:02
The issue for me is that I can reproduce the crash both with and without my mod. If it is indeed a bug in Minecraft itself caused by too many recipes, there may not be a fix available other than finding a way to reduce the overall count (which basically means removing mods, as much as I hate to say it).

It might be worth posting this in the FabricMC issue tracker to see if there's anything that can be done within the loader itself similar to what Forge did in the link above. I will try to get that created tonight, unless you want to do it.

**Comment by chimericdream** [comment] 2022-06-20 03:02
@TheButterbrotMan I just created an issue [in the Fabric repo](https://github.com/FabricMC/fabric/issues/2342). Here's hoping!

**Comment by TheButterbrotMan** [comment] 2022-06-20 10:28
Thank you! :)

**Comment by chimericdream** [comment] 2022-07-24 20:43
@TheButterbrotMan since there isn't anything specific to Minekea that we were able to determine, I am going to go ahead and close this. If it is still a problem after the recent changes to the NBT Crafting mod, and you're able to determine that there is something about Minekea in particular that causes the bug, we can reopen it.

**Closed by chimericdream** 2022-07-24 20:43 UTC
Labels: bug, blocked by Minecraft itself, third-party, 2.x, 3.x
